/**
 * Writes `src/api/routes.generated.ts`: the routes the console can call, as plain data (id,
 * method, path, which bearer, whether it sets an ETag), read from `@dhan/contracts`.
 *
 * The client needs only those five facts about a route, never its schemas. Importing `ROUTES`
 * itself shipped zod and every route's request and response schemas in the first chunk the RM
 * downloads (about 28 kB gzipped, customer-app routes included), to read five strings. The
 * registry stays the declaration: this script copies from it, the client imports the request and
 * response types from it with `import type`, `routes.generated.ts` is checked against `RouteId`
 * at compile time, and `src/api/routes.test.ts` fails if the copy and the registry disagree.
 *
 * Only routes the console holds a credential for are listed (`auth` of `none` or `rm`); a
 * customer or operator route is not in the table, so it cannot be called by mistake.
 *
 * The output is committed (unlike the theme) because `tsc` reads it; it is regenerated before
 * every dev and build run (package.json) and rewritten only when it changes.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import { ROUTES } from '@dhan/contracts'

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(HERE, '../src/api/routes.generated.ts')

/** The credentials the console holds: none, and the signed-in RM's bearer. */
export const CONSOLE_AUTH = ['none', 'rm']

export function routeTable(routes) {
  return routes
    .filter((r) => CONSOLE_AUTH.includes(r.auth))
    .map((r) => ({
      id: r.id,
      method: r.method,
      path: r.path,
      auth: r.auth,
      ...(r.cache?.etag ? { etag: true } : {}),
    }))
}

const q = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`

function render(rows) {
  const entries = rows.map((r) => {
    const fields = [
      `id: ${q(r.id)}`,
      `method: ${q(r.method)}`,
      `path: ${q(r.path)}`,
      `auth: ${q(r.auth)}`,
      ...(r.etag ? ['etag: true'] : []),
    ]
    return `  { ${fields.join(', ')} },`
  })
  return [
    '// Generated by apps/rm/scripts/routes-table.mjs from @dhan/contracts. Do not edit.',
    "import type { RouteMeta } from './route-meta.ts'",
    '',
    'export const ROUTE_TABLE = [',
    ...entries,
    '] as const satisfies readonly RouteMeta[]',
    '',
  ].join('\n')
}

/** Formatted as the repository formats TypeScript, so `prettier --check` holds on the output. */
async function format(source) {
  try {
    const prettier = await import('prettier')
    const options = (await prettier.resolveConfig(OUT)) ?? {}
    return await prettier.format(source, { ...options, filepath: OUT })
  } catch {
    return source
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const next = await format(render(routeTable(ROUTES)))
  let previous = ''
  try {
    previous = readFileSync(OUT, 'utf8')
  } catch {
    // First run.
  }
  if (previous !== next) writeFileSync(OUT, next)
  process.stdout.write(
    `routes-table: src/api/routes.generated.ts up to date (${routeTable(ROUTES).length} routes)\n`,
  )
}
