packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@expo/metro-runtime@57.0.16'
  - '@expo/ui@57.0.19'
  - expo-constants@57.0.19
  - expo-router@57.0.22
