#!/usr/bin/env bash
# Captures one real response per IDBI sandbox API, so the adapter can be mapped against what
# the bank actually sends rather than what we guessed. GENERATED — edit
# scripts/build-capture-idbi.py and regenerate, do not edit this file.
#
# Run it from a machine whose IP IDBI has allow-listed. The sandbox wants no credential; the
# allow-list is the whole gate, so a 403 here means the wrong network, not a missing key.
#
#   ./scripts/capture-idbi.sh                  # safe reads only
#   ./scripts/capture-idbi.sh --writes         # also the calls that change something
#   ./scripts/capture-idbi.sh --bureau         # also CIBIL and CKYC (needs credentials, below)
#   ./scripts/capture-idbi.sh --only 393       # redo one API
#
# Then hand back the whole output directory.
set -uo pipefail

BASE="${IDBI_BASE:-https://sandboxpocgatewayprod.idbi.bank.in}"
DELAY="${IDBI_DELAY:-1}"          # seconds between calls; the sandbox's rate limit is unknown
TIMEOUT="${IDBI_TIMEOUT:-30}"
OUT="idbi-capture-$(date +%Y%m%d-%H%M%S)"
WANT_WRITES=0
WANT_BUREAU=0
ONLY=""

while [ $# -gt 0 ]; do
  case "$1" in
    --writes) WANT_WRITES=1 ;;
    --bureau) WANT_BUREAU=1 ;;
    --only)   ONLY="${2:-}"; shift ;;
    --out)    OUT="${2:-}"; shift ;;
    -h|--help) sed -n '2,17p' "$0"; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
  shift
done

mkdir -p "$OUT" || exit 1
SUMMARY="$OUT/summary.tsv"
printf 'api\tname\tsample\ttier\thttp\tbytes\tatlas_request_id\tlabel\n' > "$SUMMARY"

ok=0; failed=0; skipped=0

printf '\n  capturing to %s\n  base %s\n\n' "$OUT" "$BASE"
printf '  %-5s %-46s %-3s %-6s %-5s %s\n' API NAME S TIER HTTP BYTES
printf '  %s\n' "----------------------------------------------------------------------------------"

call() {
  api="$1"; name="$2"; sample="$3"; tier="$4"; label="$5"; path="$6"; body="$7"

  if [ -n "$ONLY" ] && [ "$ONLY" != "$api" ]; then skipped=$((skipped+1)); return; fi
  if [ "$tier" = "writes" ] && [ "$WANT_WRITES" -eq 0 ]; then skipped=$((skipped+1)); return; fi
  if [ "$tier" = "bureau" ] && [ "$WANT_BUREAU" -eq 0 ]; then skipped=$((skipped+1)); return; fi

  # Bureau bodies carry placeholders instead of committed credentials.
  if [ "$tier" = "bureau" ]; then
    body=$(printf '%s' "$body" \
      | sed -e "s|__IDBI_CIBIL_USER__|${IDBI_CIBIL_USER:-}|g" \
            -e "s|__IDBI_CIBIL_PASS__|${IDBI_CIBIL_PASS:-}|g" \
            -e "s|__IDBI_CIBIL_MEMBER__|${IDBI_CIBIL_MEMBER:-}|g" \
            -e "s|__IDBI_CIBIL_MEMBER_PASS__|${IDBI_CIBIL_MEMBER_PASS:-}|g" \
            -e "s|__IDBI_CKYC_TOKEN__|${IDBI_CKYC_TOKEN:-}|g")
  fi

  stem="$OUT/${api}-${name}-s${sample}"
  printf '%s' "$body" > "$stem.request.json"

  http=$(printf '%s' "$body" | curl -sS -m "$TIMEOUT" -X POST "$BASE$path" \
    -H 'Content-Type: application/json' \
    -H "TransactionId: $(uuidgen 2>/dev/null || date +%s)" \
    -H 'ApplicationId: dhan-sarthi-capture' \
    -D "$stem.headers.txt" -o "$stem.response.json" \
    -w '%{http_code}' --data-binary @- 2>"$stem.curl-error.txt")
  rc=$?

  [ -s "$stem.curl-error.txt" ] || rm -f "$stem.curl-error.txt"
  if [ $rc -ne 0 ]; then http="curl:$rc"; fi

  bytes=$(wc -c < "$stem.response.json" 2>/dev/null | tr -d ' ')
  rid=$(grep -i '^x-atlas-request-id:' "$stem.headers.txt" 2>/dev/null | tr -d '\r' | awk '{print $2}')

  # Pretty-print when it is JSON, so a diff between runs is readable.
  if command -v python3 >/dev/null 2>&1; then
    python3 -c 'import json,sys;p=sys.argv[1];d=json.load(open(p));json.dump(d,open(p,"w"),indent=2,sort_keys=True)' \
      "$stem.response.json" 2>/dev/null
  fi

  printf '  %-5s %-46s %-3s %-6s %-5s %s\n' "$api" "$name" "$sample" "$tier" "$http" "${bytes:-0}"
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$api" "$name" "$sample" "$tier" "$http" "${bytes:-0}" "${rid:-}" "$label" >> "$SUMMARY"

  case "$http" in 2*) ok=$((ok+1)) ;; *) failed=$((failed+1)) ;; esac
  sleep "$DELAY"
}

call '362' 'accountLienEnquirytest' '1' 'read' 'Sample 1' '/Development/accountLienEnquirytest' '{"input":{"acctId":"660100100003","moduleType":"DEPOSIT","acctCurr":"INR","acctType":{"schmCode":"SB002","schmType":"SAVINGS"},"bankInfo":{"bankId":"IDBI001","name":"IDBIBANK","branchId":"105","branchName":"PUNE","postAddr":{"addr1":"142, Lake View","addr2":"Near City Mall","addr3":"MH","city":"PUNE","stateProv":"MH","postalCode":"411001","country":"India","addrType":"REGISTERED"}}}}'
call '362' 'accountLienEnquirytest' '2' 'read' 'Sample 2' '/Development/accountLienEnquirytest' '{"input":{"acctId":"660100100004","moduleType":"DEPOSIT","acctCurr":"INR","acctType":{"schmCode":"SB003","schmType":"SAVINGS"},"bankInfo":{"bankId":"IDBI001","name":"IDBIBANK","branchId":"106","branchName":"MUMBAI","postAddr":{"addr1":"7, Sea Breeze","addr2":"Marine Lines","addr3":"MH","city":"MUMBAI","stateProv":"MH","postalCode":"400002","country":"India","addrType":"REGISTERED"}}}}'
call '365' 'performAccountEnquirytest' '1' 'read' 'Sample 1' '/Development/performAccountEnquirytest' '{"acctId":"660100100003"}'
call '365' 'performAccountEnquirytest' '2' 'read' 'Sample 2' '/Development/performAccountEnquirytest' '{"acctId":"660100100004"}'
call '365' 'performAccountEnquirytest01' '1' 'read' 'Sample 1' '/Development/performAccountEnquirytest01' '{"acctId":"660100100006"}'
call '391' 'getLoanAccountDetailstest' '1' 'read' 'sample 1' '/Development/getLoanAccountDetailstest' '{"input":{"loanAcctId":{"acctId":"660100100003","acctType":{"schmCode":"SB002","schmType":"SAVINGS"},"acctCurr":"INR","bankInfo":{"bankId":"IDBI001","name":"IDBIBANK","branchId":"105","branchName":"PUNE","postAddr":{"addr1":"142, Lake View","addr2":"Near City Mall","addr3":"","city":"PUNE","stateProv":"MH","postalCode":"411001","country":"India","addrType":"Office"}}},"custId":{"custId":"68453002"},"channel":"API","requestId":"REQ202607160001","reqDate":"2026-07-16"}}'
call '391' 'getLoanAccountDetailstest' '2' 'read' 'Sample 2' '/Development/getLoanAccountDetailstest' '{"input":{"loanAcctId":{"acctId":"660100100004","acctType":{"schmCode":"SB003","schmType":"SAVINGS"},"acctCurr":"INR","bankInfo":{"bankId":"IDBI001","name":"IDBIBANK","branchId":"106","branchName":"MUMBAI","postAddr":{"addr1":"7, Sea Breeze","addr2":"Marine Lines","addr3":"","city":"MUMBAI","stateProv":"MH","postalCode":"400002","country":"India","addrType":"Office"}}},"custId":{"custId":"77712345"},"channel":"API","requestId":"REQ202607160002","reqDate":"2026-07-16"}}'
call '393' 'getFullAccountStatementWithPaginationtest' '1' 'read' 'sample 1' '/Development/getFullAccountStatementWithPaginationtest' '{"input":{"acid":"660100100003","branchId":"105","fromDate":"2025-05-01T00:00:00.000","toDate":"2025-05-27T00:00:00.000","sortIn":"D","paginationDetails":{"lastBalance":{"amountValue":"88955.73","currencyCode":"INR"},"lastPstdDate":"2022-12-30T22:56:49.000","lastTxnDate":"2022-12-30T00:00:00.000","lastTxnId":"S41732195","lastTxnSrlNo":"1"}}}'
call '393' 'getFullAccountStatementWithPaginationtest' '2' 'read' 'probe: first page, no cursor' '/Development/getFullAccountStatementWithPaginationtest' '{"input":{"acid":"660100100003","branchId":"105","fromDate":"2025-05-01T00:00:00.000","toDate":"2025-05-27T00:00:00.000","sortIn":"D"}}'
call '393' 'getFullAccountStatementWithPaginationtest' '3' 'read' 'probe: 10-day window, is 20 a page size' '/Development/getFullAccountStatementWithPaginationtest' '{"input":{"acid":"660100100003","branchId":"105","fromDate":"2025-05-01T00:00:00.000","toDate":"2025-05-10T00:00:00.000","sortIn":"D"}}'
call '394' 'getCustomerAccountsByCustIdtest' '1' 'read' 'sample 1' '/Development/getCustomerAccountsByCustIdtest' '{"input":{"acctType":"SBA","branchId":"105","cifId":"98655854"},"txn":"E"}'
call '394' 'getCustomerAccountsByCustIdtest01' '1' 'read' 'sample 1' '/Development/getCustomerAccountsByCustIdtest01' '{"input":{"acctType":"SBA","branchId":"107","cifId":"88234567"}}'
call '402' 'getLoanOverdueDetailstest' '1' 'read' 'sample 1' '/Development/getLoanOverdueDetailstest' '{"customerId":"98655854","accountNo":""}'
call '402' 'getLoanOverdueDetailstest01' '1' 'read' 'sample 1' '/Development/getLoanOverdueDetailstest01' '{"customerId":"88823456","accountNo":""}'
call '404' 'getLoanOverduePositionEnquirytest' '1' 'read' 'sample 1' '/Development/getLoanOverduePositionEnquirytest' '{"input":{"loanOvduPosInqCustomData":{"setId":"1234"},"asOnDate":"2026-05-27T07:08:38.194","recCtrlIn":{"maxRec":"","setNum":""},"custId":{"personName":{"lastName":"","firstName":"","name":"","middleName":"","titlePrefix":""},"custId":"68453002"},"curCode":"INR","selRangeLoanAcctId":{"lowAcctId":{"bankInfo":{"branchId":""},"acctType":{"schmCode":"","schmType":""},"acctCurr":"","acctId":"660100100003"},"highAcctId":{"bankInfo":{"branchId":"105","bankId":"","postAddr":{"stateProv":"","country":"","addr2":"","addr1":"","city":"","addr3":"","postalCode":"","addrType":""},"name":"","branchName":""},"acctType":{"schmCode":"","schmType":""},"acctCurr":"","acctId":"660100100003"}}}}'
call '404' 'getLoanOverduePositionEnquirytest' '2' 'read' 'Sample 2' '/Development/getLoanOverduePositionEnquirytest' '{"input":{"loanOvduPosInqCustomData":{"setId":"1234"},"asOnDate":"2026-05-27T07:08:38.194","recCtrlIn":{"maxRec":"","setNum":""},"custId":{"personName":{"lastName":"","firstName":"","name":"","middleName":"","titlePrefix":""},"custId":"77712345"},"curCode":"INR","selRangeLoanAcctId":{"lowAcctId":{"bankInfo":{"branchId":""},"acctType":{"schmCode":"","schmType":""},"acctCurr":"","acctId":"660100100004"},"highAcctId":{"bankInfo":{"branchId":"106","bankId":"","postAddr":{"stateProv":"","country":"","addr2":"","addr1":"","city":"","addr3":"","postalCode":"","addrType":""},"name":"","branchName":""},"acctType":{"schmCode":"","schmType":""},"acctCurr":"","acctId":"660100100004"}}}}'
# API 408: a real CIBIL pull; needs bureau credentials in the environment
call '408' 'fetchCibilScoretest' '1' 'bureau' 'sample 1' '/Development/fetchCibilScoretest' '{"fetchCibilScoreRequest":{"header":{"transactionDate":"2022-10-18T18:00:05.005","transactionId":"cibil0101","sourceSystem":"iAstra"},"body":{"dcRequest":{"authentication":{"type":"OnDemand","userId":"__IDBI_CIBIL_USER__","password":"__IDBI_CIBIL_PASS__"},"requestInfo":{"solutionSetId":368,"executeLatestVersion":true,"executionMode":"NewWithContext"},"fields":{"Applicants":{"applicants":[{"applicantType":"Individual","applicantFirstName":"PRIYA","applicantMiddleName":"","applicantLastName":"PATIL","dateOfBirth":"20061995","gender":"Female","identifiers":[{"idNumber":"","idType":""},{"idNumber":"FGHPP4567T","idType":"02"}],"telephones":[{"telephoneExtension":"","telephoneNumber":"9988776655","telephoneType":"01"}],"addresses":[{"addressLine1":"142, Lake View","addressLine2":"Near City Mall","addressType":"01","city":"PUNE","pinCode":"411001","residenceType":"01","stateCode":"27"}],"accounts":[{"accountNumber":""}]}]},"ApplicationData":{"purpose":"00","amount":10000,"scoreType":"10","GSTStateCode":"27","memberCode":"__IDBI_CIBIL_MEMBER__","password":"__IDBI_CIBIL_MEMBER_PASS__","cibilBureauFlag":false,"DSTuNtcFlag":true,"idVerificationFlag":false,"mfiBureauFlag":true,"NTCProductType":true,"consumerConsentForUIDAIAuthentication":"N","formattedReport":true}}}}}}'
# API 415: a CKYC search; needs an apiToken in the environment
call '415' 'searchCkycDetailstest' '1' 'bureau' 'sample 1' '/Development/searchCkycDetailstest' '{"input":{"apiToken":"__IDBI_CKYC_TOKEN__","parentCompany":"AAAAA8597P","searchInCkycRequestDetails":[{"queryId":"1702508","recordIdentifier":"1702508","applicationFormNo":"FF01","branchCode":"HOBRANCH","inputIdType":"C","inputIdNo":"FGHPP4567T","apiTags":"","sourceSystem":"Finacle","sourceSystemSegment":"","remarks":""}]}}'
# API 428: creates a lead in the bank
call '428' 'createLeadtest' '1' 'writes' 'sample 1 already exit lead' '/Development/createLeadtest' '{"input":{"leadType":"NEW","customerType":"INDIVIDUAL","firstName":"PRIYA","lastName":"PATIL","mobileNo":"9988776655","emailId":"priya@gmail","pancard":"FGHPP4567T","addressLine1":"142 Lake View","pincode":"411001","state":"MH","product":"Home Loan","prodCategory":"Loans","prodSubCategory":"Housing Loan","estimatedAmount":"5000000","solid":"0183","leadChannel":"Online","leadSource":"Website","leadId":"LD20260622001"}}'
call '428' 'createLeadtest' '2' 'writes' 'Sample 2 creating lead' '/Development/createLeadtest' '{"input":{"leadType":"NEW","customerType":"INDIVIDUAL","firstName":"PRIYA","lastName":"PATIL","mobileNo":"9988776655","emailId":"priya@gmail","pancard":"FGHPP4567T","addressLine1":"142 Lake View","pincode":"411001","state":"MH","product":"Car Loan","prodCategory":"Loans","prodSubCategory":"Auto Loan big","estimatedAmount":"800000","solid":"0183","leadChannel":"Online","leadSource":"Website","leadId":"LD20260622050"}}'
call '428' 'createLeadtest' '3' 'writes' 'sample 3 new pan' '/Development/createLeadtest' '{"input":{"leadType":"NEW","customerType":"INDIVIDUAL","firstName":"Amit","lastName":"Verma","mobileNo":"9123456780","emailId":"amit.verma@email.com","pancard":"ABCDX99995","addressLine1":"22 MG Road","pincode":"560001","state":"KA","product":"Personal Loan","prodCategory":"Loans","prodSubCategory":"Instant PL","estimatedAmount":"300000","solid":"0200","leadChannel":"Mobile","leadSource":"App","leadId":"LD20260622099"}}'
call '433' 'fetchLoanInterestRatestest' '1' 'read' 'sample 1' '/Development/fetchLoanInterestRatestest' '{"crncyCode":"INR","intTblCode":{"tblCode":"LY001"},"loanAmt":{"amountValue":"10000","currencyCode":"INR"},"loanPerdDays":"0","loanPerdMnths":"12","originationDate":"2022-01-03T17:13:06.751"}'
call '433' 'fetchLoanInterestRatestest' '2' 'read' 'Sample 2' '/Development/fetchLoanInterestRatestest' '{"crncyCode":"INR","intTblCode":{"tblCode":"LY002"},"loanAmt":{"amountValue":"10000","currencyCode":"INR"},"loanPerdDays":"0","loanPerdMnths":"12","originationDate":"2022-01-03T17:13:06.751"}'
call '441' 'fetchLoanAccountLimitstest' '1' 'read' 'sample 1' '/Development/fetchLoanAccountLimitstest' '{"foracid":"660100100003"}'
call '442' 'fetchCustomerLimitDetailstest' '1' 'read' 'sample 1' '/Development/fetchCustomerLimitDetailstest' '{"custCifId":"98655854"}'
call '473' 'generateLoanRepaymentScheduletest' '1' 'read' 'sample 1' '/Development/generateLoanRepaymentScheduletest' '{"loanModellingMsgInputVO":{"mandatoryParameters":{"crncyCode":"INR","originationDate":"2020-08-31T00:00:00.000","schmCode":{"schmCode":"EIDEM"}},"advanceParameters":{"eIFormula":""},"Variables":{"loanAmount":{"amountValue":"100000","currencyCode":"INR"},"intRate":{"Value":"1.2"},"noOfInstalmnts":"24"}}}'
# API 497: injects a consent event (this is an inbound webhook)
call '497' 'pushConsentNotificationtest' '1' 'writes' 'sample 1' '/Development/pushConsentNotificationtest' '{"transactionID":"1990927","timestamp":"2023-01-18T12:15:16.215Z","consentHandle":"6afdd734-be3b-475f-a8fc-3fcd18c04714","eventType":"CONSENT","eventStatus":"CONSENT_APPROVED","consentId":"CONSENT-0001","eventMessage":"Consent approved","vua":"9988776655@onemoney","productID":"TEST","accountID":"660100100003","fetchType":"PERIODIC","consentExpiry":"2027-01-17 09:47:07"}'
# API 498: injects a data event (this is an inbound webhook)
call '498' 'pushDataNotificationtest' '1' 'writes' 'sample 1' '/Development/pushDataNotificationtest' '{"transactionID":"1990927","timestamp":"2023-01-18T12:15:16.215Z","consentHandle":"6afdd734-be3b-475f-a8fc-3fcd18c04714","eventType":"DATA","eventStatus":"DATA_READY","consentId":"CONSENT-0001","vua":"9988776655@onemoney","eventMessage":"Data ready for consent id CONSENT-0001","productID":"TEST","accountID":"660100100003","fetchType":"PERIODIC","consentExpiry":"2027-01-17 09:47:07","dataExpiry":"2026-01-10T06:15:48.000Z","sessionId":"21caa19d-f69f-4954-b965-bdc1d6fc5f8a","firstTimeFetch":"false","linkRefNumbers":[{"linkRefNumber":"cf885ed4-3085-45db-bd65-f9472d0073a4","fiStatus":"READY","fipName":"IDBI Bank","fipId":"IDBI001","maskedAccountNumber":"XXXXXXXX0003"}]}'
# API 508: may send an OTP (otpRequired=Y); bank-staff data, not our users
call '508' 'fetchHRMSEmployeeDetailstest' '1' 'writes' 'sample 1' '/Development/fetchHRMSEmployeeDetailstest' '{"ein":"137075","otpRequired":"Y","channelName":"MOBILE_APP"}'
call '538' 'InquireHPAyofftest' '1' 'read' 'sample 1' '/Development/InquireHPAyofftest' '{"hPayOffInq":{"foracid":"660100100003"}}'
# API 590: creates a consent request, may notify the customer
call '590' 'requestConsentFromFinProtest' '1' 'writes' 'sample 1' '/Development/requestConsentFromFinProtest' '{"partyIdentifierType":"MOBILE","partyIdentifierValue":"9988776655","productID":"TEST","accountID":"660100100003","vua":"9988776655@onemoney","transactionID":"9080"}'
call '591' 'getConsentListFromFinProtest' '1' 'read' 'sample 1' '/Development/getConsentListFromFinProtest' '{"partyIdentifierType":"MOBILE","partyIdentifierValue":"9988776655","productID":"TEST","accountID":"660100100003","vua":"9988776655@onemoney"}'
call '591' 'getConsentListFromFinProtest01' '1' 'read' 'sample 1' '/Development/getConsentListFromFinProtest01' '{"partyIdentifierType":"MOBILE","partyIdentifierValue":"9765400022","productID":"TEST","accountID":"660100100006","vua":"9765400022@onemoney"}'
call '591' 'getConsentListFromFinProtest01' '2' 'read' 'Sample 2' '/Development/getConsentListFromFinProtest01' '{"partyIdentifierType":"MOBILE","partyIdentifierValue":"9765400022","productID":"TEST","accountID":"660100100007","vua":"9765400022@onemoney"}'
call '591' 'getConsentListFromFinProtest01' '3' 'read' 'Sample 3' '/Development/getConsentListFromFinProtest01' '{"partyIdentifierType":"MOBILE","partyIdentifierValue":"9765400022","productID":"TEST","accountID":"660100100008","vua":"9765400022@onemoney"}'
call '591' 'getConsentListFromFinProtest01' '4' 'read' 'Sample 4' '/Development/getConsentListFromFinProtest01' '{"partyIdentifierType":"MOBILE","partyIdentifierValue":"9765400022","productID":"TEST","accountID":"660100100009","vua":"9765400022@onemoney"}'
call '592' 'getWebRedirectionEncryptedURLtest' '1' 'read' 'sample 1' '/Development/getWebRedirectionEncryptedURLtest' '{"consentHandle":"6afdd734-be3b-475f-a8fc-3fcd18c04714","redirectUrl":"https://myapp.com/consent/callback"}'
call '593' 'generateDecryptedResponseFromFinProtest' '1' 'read' 'sample 1' '/Development/generateDecryptedResponseFromFinProtest' '{"webRedirectionURL":{"ecres":"0cxcJYX2p0TUjgqwGtPr3_C7uABITDhYa-ObDOmO1WeoURQ-HuuNH9dXFKdnp9Gj_7TxtyAwdfC9wEbJ_7nK9TDGpCECi5s_7hzT76WLCsmNQZWLPeacHAmp5hhUyaAhOf8ZBvNL8q3jTumXRPaghp8gVgwoJC4HXZ6rHNwirC_kTWoxoXtFElUwsCpm_1iGeVZ7C1l_MY8B3rrqhrbVAOLqBnjweSyCHB4B6rqoX3iPCYOuw88XzkToXTSHJuoycwD0rSO9q134ntNTkBsZ_gonG1PRIBQaPi38mWtRpCzA8cfmHteguRHWmGRIOm35v","resdate":"100720230858407","fi":"Xl5VWl1eV0odWVQ"}}'
call '595' 'getAccountStatementtest' '1' 'read' 'sample 1' '/Development/getAccountStatementtest' '{"consentId":"CONSENT-0001","linkRefNumber":["19818fc6-d5ee-429b-9d14-4dfd5d92fc8e"]}'
call '595' 'getAccountStatementtest01' '1' 'read' 'sample 1 saving account' '/Development/getAccountStatementtest01' '{"consentId":"CONSENT-0003-SAV","linkRefNumber":["lr-003-sav-0001-11aa22bb33cc"]}'
call '595' 'getAccountStatementtest01' '2' 'read' 'sample 2 cuurent account' '/Development/getAccountStatementtest01' '{"consentId":"CONSENT-0003-CUR","linkRefNumber":["lr-003-cur-0002-44dd55ee66ff"]}'
call '595' 'getAccountStatementtest01' '3' 'read' 'sample 3 fix deposit account' '/Development/getAccountStatementtest01' '{"consentId":"CONSENT-0003-FD","linkRefNumber":["lr-003-fd-0003-77gg88hh99ii"]}'
call '595' 'getAccountStatementtest01' '4' 'read' 'Sample 4 salary account' '/Development/getAccountStatementtest01' '{"consentId":"CONSENT-0003-SAL","linkRefNumber":["lr-003-sal-0004-00jj11kk22ll"]}'
call '739' 'getAccountStatementFromFinProtest' '1' 'read' 'sample 1' '/Development/getAccountStatementFromFinProtest' '{"consentId":"CONSENT-0001","linkRefNumber":["76ae28bd-eebf-4a49-8701-68a14346d996"]}'

printf '\n  %s\n' "----------------------------------------------------------------------------------"
printf '  ok %s   failed %s   skipped %s\n' "$ok" "$failed" "$skipped"
printf '  summary: %s\n' "$SUMMARY"

if [ "$failed" -gt 0 ] && [ "$ok" -eq 0 ]; then
  printf '\n  Everything failed. If the responses are HTML 403 from awselb, this machine is not\n'
  printf '  on the IDBI allow-list rather than missing a key.\n'
fi

printf '\n  Hand back the whole directory:\n    tar -czf %s.tar.gz %s\n\n' "$OUT" "$OUT"
