import { useEffect, useRef, useState } from 'react'
import { advisorQA } from '../data.js'

export default function Advisor({ speak, onToast }) {
  const [messages, setMessages] = useState([
    { who: 'bot', text: 'Ask me anything about your money. If a question needs a human — complex tax, estate planning, or if you just prefer a person — I\'ll hand you to an IDBI relationship manager with full context.' },
  ])
  const [asked, setAsked] = useState([])
  const [typing, setTyping] = useState(false)
  const endRef = useRef(null)

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages, typing])

  const ask = (qa) => {
    setMessages((m) => [...m, { who: 'user', text: qa.q }])
    setAsked((a) => [...a, qa.q])
    setTyping(true)
    setTimeout(() => {
      setTyping(false)
      setMessages((m) => [...m, { who: 'bot', text: qa.a, fineprint: qa.basis }])
      speak(qa.a)
    }, 900)
  }

  const remaining = advisorQA.filter((qa) => !asked.includes(qa.q))

  return (
    <div className="body">
      <div className="chat-scroll" style={{ paddingTop: 8 }}>
        {messages.map((m, i) => (
          <div key={i} className={`msg ${m.who}`}>
            {m.text}
            {m.fineprint && <span className="fineprint">{m.fineprint}</span>}
          </div>
        ))}
        {typing && <div className="msg bot typing"><i /><i /><i /></div>}
        {!typing && remaining.length > 0 && (
          <div className="chips">
            {remaining.map((qa) => (
              <button key={qa.q} onClick={() => ask(qa)}>{qa.q}</button>
            ))}
          </div>
        )}
        <div ref={endRef} />
      </div>

      <div className="h-section">Prefer a human?</div>
      <div className="card rm-card">
        <div className="face">🧑‍💼</div>
        <div className="tx">
          <b>Talk to your relationship manager</b><br />
          Sarthi shares your goals & risk profile (with consent), so you never repeat yourself.
        </div>
        <button
          className="btn ghost" style={{ width: 'auto', padding: '9px 13px', fontSize: 12 }}
          onClick={() => onToast('✓ Callback booked for <b>today, 6:00 pm</b>. Your Sarthi summary has been shared with RM Priya Nair.')}
        >
          Book
        </button>
      </div>
      <div className="disclaimer">
        Responses generated by AI and logged for compliance review. Escalation rules ensure
        complex or distressed cases always reach a human.
      </div>
    </div>
  )
}
