import { spendCategories, spendTotal, insights, nudges, persona, formatINR } from '../data.js'

const seriesVars = ['--series-1', '--series-2', '--series-3', '--series-4', '--series-5']
const maxSpend = Math.max(...spendCategories.map((c) => c.amount))

export default function Dashboard({ onToast, goPlan }) {
  return (
    <div className="body">
      <div className="hero">
        <div className="label">This month, your money left idle</div>
        <div className="big">{formatINR(insights.avgMonthlySurplus)}</div>
        <div className="sub">
          After rent, bills and lifestyle, this is what you consistently don't spend —
          earning ~3% in savings while inflation runs ~6%. <b>Future-you would invest it.</b>
        </div>
      </div>

      <div className="h-section">Where last month went · ₹{spendTotal.toLocaleString('en-IN')}</div>
      <div className="card barlist">
        {spendCategories.map((c, i) => (
          <div className="row" key={c.name}>
            <div className="name">{c.name}</div>
            <div className="track">
              <div
                className="fill"
                style={{ width: `${(c.amount / maxSpend) * 100}%`, background: `var(${seriesVars[i]})` }}
              />
            </div>
            <div className="val">₹{c.amount.toLocaleString('en-IN')}</div>
          </div>
        ))}
      </div>

      <div className="h-section">Sarthi noticed</div>
      {nudges.map((n) => (
        <div className="card nudge" key={n.action}>
          <div className="ic">{n.icon}</div>
          <div>
            <div className="tx" dangerouslySetInnerHTML={{ __html: n.text }} />
            <div className="act">
              <button onClick={() => (n.action.includes('SIP') ? goPlan() : onToast(`✓ Noted — <b>${n.action}</b> queued. A summary and consent request will arrive before anything changes.`))}>
                {n.action} →
              </button>
            </div>
          </div>
        </div>
      ))}

      <div className="disclaimer">
        Insights are generated by AI from your consented transaction data (RBI Account Aggregator ·
        DPDP Act 2023). {persona.name}'s data shown is illustrative.
      </div>
    </div>
  )
}
